import { ServicesProvider } from "@/providers/servicesProvider";
import { StoreProvider } from "@/providers/storeProvider";
import { ThemesProvider } from "@/providers/themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UiLibraryProviders } from "../providers/ui_library";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import { SocketProvider } from "@/providers/SocketProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemesProvider>
          <ServicesProvider>
            {/* <SocketProvider> */}
            <StoreProvider>
              <UiLibraryProviders>{children}</UiLibraryProviders>
            </StoreProvider>
            {/* </SocketProvider> */}
          </ServicesProvider>
        </ThemesProvider>
      </body>
    </html>
  );
}
